server:
  port: 10001

spring:
  application:
    name: mszlu_blog
  datasource:
    url: jdbc:mysql://192.168.19.134:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.19.134
    port: 6379
  # 上传文件总的最大值
#  servlet:
#    multipart:
#      max-request-size: 20MB
#      # 单个文件最大值
#      max-file-size: 2MB
mybatis-plus:
  # Mapper
  mapper-locations:
    classpath*:/mapper/**Mapper.xml
  # 打印日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 数据库表前缀,查询表的时候会自动加上这个前缀
    db-config:
      table-prefix: ms_


